name: Deploy info

# If there is a PR from a fork which has been approved to run GitHub Actions,
# that PR's head is pushed to a branch directly in the repo (not the fork),
# so it's deployed by Cloudflare Pages as a branch preview.

on:
  workflow_dispatch:
    inputs:
      simulate_fork_pr:
        description: 'Simulate fork for this PR number'
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: read

jobs:
  deploy-info:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: >
      inputs.simulate_fork_pr ||
      github.event.pull_request.head.repo.full_name != github.repository

    concurrency:
      group: deploy-${{ github.event.inputs.simulate_fork_pr || github.event.number }}

    steps:
      - uses: actions/checkout@v4

      - name: Push to internal branch
        run: |
          git fetch origin ${{ github.sha }}
          git push "https://user:${{ secrets.PUSH_GITHUB_TOKEN }}@github.com/${{ github.repository }}" ${{ github.sha }}:refs/heads/deploy/${{ inputs.simulate_fork_pr || github.event.number }}
