name: Deploy cleanup

# NOTE: This workflow triggers the `deploy-cleanup-run.yml` workflow.

on:
  workflow_dispatch:
    inputs:
      simulate_fork_pr:
        description: 'Simulate fork for this PR number'
  pull_request:
    types: [ closed ]
    branches: [ main, features/** ]

jobs:
  deploy-cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: >
      inputs.simulate_fork_pr ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ inputs.simulate_fork_pr || github.event.number }} > ./pr/pr_number

      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/
